## Numpy

In [1]:
# Importar a biblioteca numpy
import numpy as np

In [2]:
# Criar uma matriz unidimensional
mt = np.array([12, 34, 26, 18, 10])
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [3]:
# Criar um array com um tipo específico (float de 64 bits)
mtfloat = np.array([1, 2, 3], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [4]:
# Criar um array com um tipo específico (inteiro de 32 bits)
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
# Modificar o tipo do array (casting)
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# Quando transformamos de float64 para int32 os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [6]:
# Podemos fazer o inverso
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [7]:
# Criar uma matriz bidimensional
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [8]:
# Criar arrays vazios tipificados
# empty() - Significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)

[[         0 1072693248]
 [         0 1073741824]
 [         0 1074266112]]


In [9]:
# Criar uma matriz 4x3 com valores zero
# zeros()
zeros = np.zeros([4,3])
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
# Criar uma matriz com valores igual a 1
# ones()
um = np.ones([5,7])
print(um)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [11]:
# Criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero
# eye()
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
# Valores aleatórios entre zero e um
# random()
ale = np.random.random((5))
print(ale)

[0.72747618 0.81185202 0.72679059 0.03800688 0.85677461]


In [13]:
# Valores aleatórios distr. normal contendo negativos
# randn()
ale2= np.random.randn((5))
print(ale2)

[ 0.13438171 -0.54841933 -0.20091227 -1.38716166 -0.44858279]


In [14]:
# Valores aleatórios 3 x 4
ale3 = (10 * np.random.random((3, 4)))
print(ale3)

[[6.14929287 6.60126557 5.59720713 6.02235599]
 [9.04741524 2.74138806 2.16682335 9.74431065]
 [9.1989569  2.0223965  8.89503974 4.79230499]]


In [15]:
# Valores aleatórios com uso de semente (obterá a mesma sequência de números aleatórios)
# default_rng()
gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print (ale5)

[0.51182162 0.9504637  0.14415961]


In [16]:
# Valores aleatórios inteiros
# integers()
ale6 = gnr.integers(10, size=(3, 4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [17]:
# unique() - Remover repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [18]:
# Funções específicas
k = np.array([[17, 22, 43], [27, 25, 14], [15, 24, 32]])
# Mostrar a matriz k
print(k)

# Mostrar um elemento específico da matriz k (linha, coluna)
print(k[0][1])

# Mostrar o tamanho das dimensões da matriz k
print(k.shape)

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)


In [19]:
# Funções matemáticas
# Retonar o maior valor da matriz k
print(k.max())

# Retornar o menor valor da matriz k
print(k.min())

# Retornar a soma dos valores da matriz k
print((k.sum()))

# Retornar o valor da média dos valores da matriz k
print(k.mean())

# Retornar o valor do desvio padrão (standard deviation) dos valores da matiz k
print(k.std())

43
14
219
24.333333333333332
8.615231988880057


In [20]:
# Funções universais (aplicadas a cada um dos elementos)
k1 = np.array([1, 4, 9, 16, 25, 36])
# Mostrar o valor da raiz quadrada de todos elementos
print(np.sqrt(k1))

# Mostrar o valor do exponencial de todos elementos
print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [21]:
# Extração de elementos (fatiamento e slicing)
m = np.array([1, 2, 3, 4, 5, 6])
# Mostrar o elemento da posição 2
print(m[1])

# Mostrar o array criado a partir do índice 0, dois elementos
print(m[0:2])

# Mostrar o array criado a partir do índice 1 até todo o restante do array
print(m[1:])

# Mostrar o array criado a partir da penúltima posição até o final
print(m[-2:])

# Mostrar o array criado a partir do índice 0 até a penúltima posição
print(m[:-2])

2
[1 2]
[2 3 4 5 6]
[5 6]
[1 2 3 4]


In [22]:
# Extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)

# Primeira linha, todas as colunas
l_linha_1 = l[0, :]
print(l_linha_1)

# Segunda linha, todas as colunas
l_linha_2 = l[1, :]
print(l_linha_2)

# Terceira linha, todas as colunas
l_linha_3 = l[2, :]
print(l_linha_3)

# Todas as linhas, primeira coluna
l_coluna_1 = l[:, 0]
print(l_coluna_1)

# Todas as linhas, segunda coluna
l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[7 4]
[4 6 7]
[5 1 4]


In [23]:
# Adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
print(n)
print(o)
# Adição das matrizes
soma_matriz = n + o
print(soma_matriz)

# Multiplicação das matrizes
mult_matriz = n * o
print(mult_matriz)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]
[[2 3]
 [4 5]]
[[1 2]
 [3 4]]


In [24]:
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p)
print(q)
print(p+q)

[[1 2]
 [3 4]
 [5 6]]
[[2 1]]
[[3 3]
 [5 5]
 [7 7]]


In [25]:
# Transposição
# Rearranja um conjunto de 15 elementos de 0 a 14 em 3 linhas e 5 colunas)
f = np.arange(15).reshape((3, 5))
print(f)

# Mostrar a matriz transposta entre linha e coluna (usando .T)
s = f.T
print(s)

# Mostrar a matriz transposta entre linha e coluna (usando .transpose())
t = f.transpose((1,0))
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [26]:
# Expressões lógicas
# Criar matriz 4x4 com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)

# Criar matriz com valores -1 e 1 baseado nos valores do array v
y = np.where(v > 0, 1, -1)
print(y)

# Criar matriz com valores booleanos baseado no array v (False=Negativo , True=Positivo)
x = (v > 0)
print(x)

# Criar matriz com valores -1 e 1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[ 0.95391462  0.43911697 -0.52333122  1.1451992 ]
 [-0.76018943  1.0418806   0.58402028 -0.24066954]
 [ 1.94613459 -1.13770776 -1.25172074  0.43294964]
 [ 0.47027159  0.88076443 -0.84920222  0.60788869]]
[[ 1  1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [ 1  1 -1  1]]
[[ True  True False  True]
 [False  True  True False]
 [ True False False  True]
 [ True  True False  True]]
[[ 1  1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [ 1  1 -1  1]]
